// This file contains hashes of SQLite binaries downloaded by the default hook.
// For tests, it is replaced with actual assets. For releases, a pre-release
// check asserts it's up-to-date.
//
// Generated by tool/write_asset_hashes.dart

// dart format off
// ignore: unnecessary_nullable_for_final_variable_declarations
const String? releaseTag = null;

const Map<String, String> assetNameToSha256Hash = {
  'libsqlcipher.arm.android.so': '3a82023af6b6b1017f36cb3d5e392a139caaa0fb0caa8f75a3267e975bad999f',
  'libsqlcipher.arm64.android.so': '0a260058d111a6e1b7a4fea867aab77051320c9fda8e540dd575691a630e9749',
  'libsqlcipher.arm64.ios.dylib': 'eaf7ab353ab44c3e0925fbc24f09e37fe54444dd1b31612ab6149ef18bb6546d',
  'libsqlcipher.arm64.ios_sim.dylib': '5bcb889ababa7db300cbb15c528e96641fc4cc1d066f3e29cb373c7cbc3acc35',
  'libsqlcipher.arm64.macos.dylib': '8a9760e655f995b425c42b94a3f4413425d9c420c260e067bdd52e9552e2acfe',
  'libsqlcipher.ia32.android.so': '83ac3139701c02fdec9555818a032d30cfa423afef019f58ee51c5415b5bfd79',
  'libsqlcipher.x64.android.so': '7a848acf975dc0ac4b0eac24d751eebc0fd591e0f7f480a20453d0787dd33a6d',
  'libsqlcipher.x64.ios_sim.dylib': 'b1ffb9e4685dc263e1d5e8a074a196dbae49710af63cf8882ce50561850debb8',
  'libsqlcipher.x64.linux.so': 'eeb091f42a68dd6bb66fe414106cb776c39c0de21d54d845188f629984207303',
  'libsqlcipher.x64.macos.dylib': '0d46036001cd2ad146fd65df09791a36d96ad8c94403ffe64ffcfca54d09ebff',
  'sqlite3.debug.wasm': '9a942f7c42247e6463725b80bafc3a3f5d1ff6a6d2d27ef1ba1b06a313bf0a2e',
  'sqlite3.wasm': 'cb6b6b3a6d6cd912ef3b95ab995714a4e91694aa9a9d1cd15542314fb44982d0',
  'sqlite3mc.wasm': '4493f8b822215a3ac50364deb0e5a0491bd6ec537c0f79ee2ef1fb02575ffbdd',
};
